server {
  listen 3000;
  server_name dev.frontendmcp.com;
  
  include       mime.types;
  default_type  application/octet-stream;
  sendfile      on;
  server_tokens off;
  etag off;
  add_header X-Powered-By "" always;
  more_clear_headers 'Server';

location = /worker {
  limit_except GET { deny all; }
  default_type text/html;
  brotli_static on;
  zstd_static on;
  gzip_static on;
  alias /usr/share/nginx/html/worker/worker.html;
  more_set_headers "Content-Security-Policy: default-src 'none'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; connect-src wss://mcp.frontendmcp.com; base-uri 'none'; form-action 'none';";
  more_clear_headers 'X-Frame-Options';
  }

  location / {
    return 404;
  }

}