server {
  listen 80;
  server_name functionbridge.com;

  include       mime.types;
  default_type  application/octet-stream;
  sendfile      on;
  server_tokens off;
  etag off;
  add_header X-Powered-By "" always;
  more_clear_headers 'Server';

  location /worker {
    limit_except GET { deny all; }
    brotli_static on;
    zstd_static on;
    gzip_static on;
    root /usr/share/nginx/html;
    index worker.html;
    add_header Content-Security-Policy "default-src 'none'; script-src 'self'; connect-src https://mcp.frontendmcp.com; img-src data:; style-src 'unsafe-inline'; frame-ancestors 'none';";
  }

}